elf: Fix dl-cache.c build with clang-23
clang-23 warns that the variable 'ext' set but not used:

  dl-cache.c:42:47: error: variable 'ext' set but not used
  [-Werror,-Wunused-but-set-global]

The variable is set unconditionally by _dl_load_cache_lookup, but it
is only read by glibc_hwcaps_priorities_init (which is compiled only
for SHARED).