string: Drop always_inline from tst-xbzero-opt [BZ #23130]
Commit a066c5d7d keeps always_inline on prepare_test_buffer unless the
compiler lacks indirect_return, as a proxy for swapcontext not being
returns_twice.  GCC has indirect_return on RISC-V, which uses the
generic bits/indirect-return.h, so the test asks to inline a caller of
a returns_twice function and fails to build:

  tst-xbzero-opt.c:122:1: error: function 'prepare_test_buffer' can
  never be inlined because it uses setjmp

Remove the attribute and the condition around it.

Tested on x86_64 and sparc64.

Reported-by: Andreas Schwab <schwab@suse.de>
Signed-off-by: Stian Halseth <stian@itx.no>
Reviewed-by: Adhemerval Zanella  <adhemerval.zanella@linaro.org>